[package]
name = "nmos-rs-model"
version = "0.1.0"
edition = "2021"

[dependencies]
nmos-rs-schema = { path = "../schema" }
tokio = { version = "1", features = ["sync"] }
uuid = { version = "1", features = ["v4"] }
serde_json = "1"
