[package]
name = "nmos-rs-schema"
version = "0.1.0"
edition = "2021"

[dependencies]
schemafy = "0.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[build-dependencies]
convert_case = "0.6"
serde_json = "1"
