[package]
name = "nmos-schema"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
uuid = { version = "1", features = ["serde"] }

[dev-dependencies]
serde_json = "1"
